# Generated by Django 5.2 on 2025-09-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0003_product_delete_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fruits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=264, unique=True)),
                ("title", models.CharField(max_length=264, unique=True)),
                ("description", models.TextField(unique=True)),
                ("content", models.TextField(unique=True)),
                ("image", models.TextField()),
            ],
        ),
    ]
