# Generated by Django 5.2.6 on 2025-09-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_fruits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fruits',
            new_name='Category',
        ),
    ]
