# Generated by Django 5.2.6 on 2025-09-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_rename_fruits_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('price', models.IntegerField()),
                ('image', models.TextField()),
            ],
        ),
    ]
