# Generated by Django 5.2.6 on 2025-09-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_fruit_description_fruit_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='title',
        ),
    ]
