# Generated by Django 5.2.6 on 2025-09-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_remove_fruit_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='description',
        ),
    ]
