# Generated by Django 5.2.6 on 2025-09-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_remove_fruit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='description',
            field=models.TextField(default='no description', unique=True),
            preserve_default=False,
        ),
    ]
