# Generated by Django 5.2.6 on 2025-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_fruit_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='description',
        ),
        migrations.AddField(
            model_name='fruit',
            name='title',
            field=models.CharField(default='no description', max_length=264, unique=True),
            preserve_default=False,
        ),
    ]
